#!/bin/bash

echo "🔍 Checking logging system..."
echo ""

# Check if we're in the right directory
if [ ! -f "package.json" ]; then
    echo "❌ Please run this from the addin-project directory"
    exit 1
fi

# Check if log server is running
echo "1. Testing log server..."
if curl -k -s https://localhost:3001/api/health > /dev/null 2>&1; then
    echo "✅ Log server is running (HTTPS)"
    response=$(curl -k -s https://localhost:3001/api/health)
    echo "   Response: $response"
elif curl -s http://localhost:3001/api/health > /dev/null 2>&1; then
    echo "⚠️  Log server is running (HTTP fallback)"
    response=$(curl -s http://localhost:3001/api/health)
    echo "   Response: $response"
else
    echo "❌ Log server is NOT running"
    echo "   Start it with: npm run log-server"
    echo ""
fi

# Check logs directory
echo ""
echo "2. Checking logs directory..."
if [ -d "logs" ]; then
    echo "✅ Logs directory exists"
    log_count=$(ls -1 logs/ 2>/dev/null | wc -l)
    echo "   Contains $log_count log files"
    if [ $log_count -gt 0 ]; then
        echo "   Latest files:"
        ls -lt logs/ | head -3
    fi
else
    echo "❌ Logs directory does not exist"
    echo "   It will be created when the log server starts"
fi

# Test saving a log
echo ""
echo "3. Testing log save..."
test_session="test-$(date +%s)"
test_data="{\"sessionId\":\"$test_session\",\"markdown\":\"# Test Log\\n\\nGenerated by check script at $(date)\\n\"}"

if curl -k -s https://localhost:3001/api/save-log -H "Content-Type: application/json" -d "$test_data" > /dev/null 2>&1; then
    echo "✅ Successfully saved test log (HTTPS)"
    if [ -f "logs/analysis-$test_session.md" ]; then
        echo "✅ Test log file confirmed in logs directory"
        echo "   File: logs/analysis-$test_session.md"
    else
        echo "❌ Test log file not found in logs directory"
    fi
elif curl -s http://localhost:3001/api/save-log -H "Content-Type: application/json" -d "$test_data" > /dev/null 2>&1; then
    echo "✅ Successfully saved test log (HTTP fallback)"
    if [ -f "logs/analysis-$test_session.md" ]; then
        echo "✅ Test log file confirmed in logs directory"
        echo "   File: logs/analysis-$test_session.md"
    else
        echo "❌ Test log file not found in logs directory"
    fi
else
    echo "❌ Failed to save test log"
fi

echo ""
echo "🎯 Quick commands:"
echo "   Start with logging: npm run start-with-logs"
echo "   Check logs:         ls -la logs/"
echo "   Open logs folder:   open logs/"
